<?php
/**
 * CustomValidation
 * PHP version 7.4
 *
 * @category Class
 * @package  Dana\Disbursement\v1
 * @author   DANA Indonesia
 * @link     https://dashboard.dana.id/
 */

/**
 * Disbursement API
 *
 * API for doing operations related to Disbursement
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

namespace Dana\Disbursement\v1;

use Dana\ApiException;
use Dana\Disbursement\v1\Model\BankAccountInquiryRequest;
use Dana\Disbursement\v1\Model\DanaAccountInquiryRequest;
use Dana\Disbursement\v1\Model\TransferToBankRequest;
use Dana\Disbursement\v1\Model\TransferToDanaRequest;

/**
 * CustomValidation Class
 *
 * This class provides custom validation functions for Disbursement API requests.
 * Validations are registered in the validationRegistry and executed via CustomValidation().
 */
class CustomValidation
{
    /**
     * Validation registry maps request class names to their validation functions
     *
     * @var string[]
     */
    /** Sandbox-only allowed beneficiary account number */
    private const SANDBOX_BENEFICIARY_ACCOUNT_NUMBER = '2460888509';

    /** Sandbox-only allowed beneficiary bank code */
    private const SANDBOX_BENEFICIARY_BANK_CODE = '014';

    /** Sandbox maximum amount (major units) for Disbursement. */
    private const SANDBOX_MAX_AMOUNT = 20000000;

    /** Allowed accountType enum values. */
    private const ALLOWED_ACCOUNT_TYPES = [
        'MERCHANT_DEPOSIT_ACCOUNT',
        'SETTLEMENT_ACCOUNT',
        'DIVISION_DEPOSIT_ACCOUNT',
    ];

    private static $validationRegistry = [
        'Dana\Disbursement\v1\Model\BankAccountInquiryRequest' => [
            'stripSandboxIgnoredFieldsBankAccountInquiry',
            'validateAccountTypeBankAccountInquiry',
            'validateSandboxBeneficiaryBankAccountInquiry',
            'validateSandboxAmount',
            'validateRequiredAdditionalInfoNotEmptyBankAccountInquiry',
        ],
        'Dana\Disbursement\v1\Model\TransferToBankRequest' => [
            'stripSandboxIgnoredFieldsTransferToBank',
            'validateAccountTypeTransferToBank',
            'validateSandboxBeneficiaryTransferToBank',
            'validateSandboxAmount',
            'validateRequiredAdditionalInfoNotEmptyTransferToBank',
        ],
        'Dana\Disbursement\v1\Model\TransferToDanaRequest' => [
            'stripSandboxIgnoredFieldsTransferToDana',
            'validateAccountTypeTransferToDana',
            'validateSandboxAmount',
            'validateRequiredAdditionalInfoNotEmptyTransferToDana',
        ],
        'Dana\Disbursement\v1\Model\DanaAccountInquiryRequest' => [
            'stripSandboxIgnoredFieldsDanaAccountInquiry',
            'validateSandboxAmount',
            'validateRequiredAdditionalInfoNotEmptyDanaAccountInquiry',
        ],
    ];

    /**
     * Perform custom validations / mutations on the request based on its type
     *
     * @param mixed $request The request object to validate (can be any type)
     * @return void
     * @throws ApiException if validation fails
     */
    public static function validate($request)
    {
        if ($request === null) {
            return;
        }

        $className = get_class($request);

        if ($request instanceof BankAccountInquiryRequest) {
            $className = 'Dana\Disbursement\v1\Model\BankAccountInquiryRequest';
        } elseif ($request instanceof TransferToBankRequest) {
            $className = 'Dana\Disbursement\v1\Model\TransferToBankRequest';
        } elseif ($request instanceof TransferToDanaRequest) {
            $className = 'Dana\Disbursement\v1\Model\TransferToDanaRequest';
        } elseif ($request instanceof DanaAccountInquiryRequest) {
            $className = 'Dana\Disbursement\v1\Model\DanaAccountInquiryRequest';
        }

        if (!isset(self::$validationRegistry[$className])) {
            return;
        }

        $messages = [];
        foreach (self::$validationRegistry[$className] as $validatorName) {
            if (!method_exists(self::class, $validatorName)) {
                continue;
            }
            try {
                self::$validatorName($request);
            } catch (ApiException $e) {
                $messages[] = $e->getMessage();
            }
        }

        if (!empty($messages)) {
            throw new ApiException(
                'validation failed: ' . implode('; ', $messages),
                0,
                null,
                null
            );
        }
    }

    private const SANDBOX_DANA_BALANCE_LIMIT_HINT =
        'Make sure DANA balance not exceeding limit of 21000000 after topup';

    /**
     * Augment TransferToDana responses in sandbox on business errors.
     *
     * @param mixed $request
     * @param mixed $response
     * @return void
     */
    public static function processResponse($request, $response)
    {
        if (!self::isSandbox() || $request === null || $response === null) {
            return;
        }
        if (!($request instanceof TransferToDanaRequest)) {
            return;
        }
        if (!method_exists($response, 'getResponseMessage') || !method_exists($response, 'offsetSet')) {
            return;
        }
        $responseCode = method_exists($response, 'getResponseCode') ? (string) $response->getResponseCode() : '';
        if (!self::isBusinessErrorResponse($responseCode)) {
            return;
        }
        $response->offsetSet(
            'responseMessage',
            self::appendSandboxHint(
                $response->getResponseMessage(),
                self::SANDBOX_DANA_BALANCE_LIMIT_HINT,
                '21000000',
                'after topup'
            )
        );
    }

    /**
     * Enrich TransferToDana HTTP errors in sandbox.
     *
     * @param mixed $request
     * @param ApiException $e
     * @return ApiException
     */
    public static function enrichTransferToDanaError($request, ApiException $e)
    {
        if (!self::isSandbox() || !($request instanceof TransferToDanaRequest)) {
            return $e;
        }
        $body = (string) $e->getResponseBody();
        if ($body === '') {
            return $e;
        }
        try {
            $payload = json_decode($body, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $ignore) {
            return $e;
        }
        if (!is_array($payload)) {
            return $e;
        }
        $response = new \Dana\Disbursement\v1\Model\TransferToDanaResponse([
            'responseCode' => isset($payload['responseCode']) ? (string) $payload['responseCode'] : '',
            'responseMessage' => isset($payload['responseMessage']) ? (string) $payload['responseMessage'] : '',
            'partnerReferenceNo' => isset($payload['partnerReferenceNo']) ? (string) $payload['partnerReferenceNo'] : '',
        ]);
        self::processResponse($request, $response);
        $enriched = new ApiException($e->getMessage(), $e->getCode(), $e->getResponseHeaders(), $e->getResponseBody());
        $enriched->setResponseObject($response);
        return $enriched;
    }

    private static function isBusinessErrorResponse(string $responseCode): bool
    {
        $code = trim($responseCode);
        return $code === '' || strpos($code, '200') !== 0;
    }

    /**
     * Always append hint (Go-compatible).
     *
     * @param string|null $responseMessage
     * @param string $hint
     * @param string ...$alreadyPresentMarkers
     * @return string
     */
    private static function appendSandboxHint($responseMessage, string $hint, string ...$alreadyPresentMarkers): string
    {
        $msg = trim((string) $responseMessage);
        $lowerMsg = strtolower($msg);
        foreach ($alreadyPresentMarkers as $marker) {
            if ($marker !== '' && strpos($lowerMsg, strtolower($marker)) !== false) {
                return $msg;
            }
        }
        if ($msg === '') {
            return $hint;
        }
        if (substr($msg, -1) === '.') {
            return $msg . ' ' . $hint;
        }
        return $msg . '. ' . $hint;
    }

    private static function isSandbox(): bool
    {
        $env = getenv('DANA_ENV') ?: getenv('ENV') ?: 'sandbox';
        return strtolower($env) === 'sandbox';
    }

    /**
     * In sandbox, amount.value must not exceed SANDBOX_MAX_AMOUNT.
     *
     * @param mixed $request The request to validate
     * @return void
     * @throws ApiException if validation fails
     */
    private static function validateSandboxAmount($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        if (!method_exists($request, 'getAmount')) {
            return;
        }
        $amount = $request->getAmount();
        if ($amount === null || !method_exists($amount, 'getValue')) {
            return;
        }
        $value = $amount->getValue();
        if ($value === null || trim((string) $value) === '') {
            return;
        }
        if (!is_numeric($value)) {
            return;
        }
        if ((float) $value > self::SANDBOX_MAX_AMOUNT) {
            throw new ApiException(
                'in sandbox, amount.value must not exceed ' . self::SANDBOX_MAX_AMOUNT . '; got ' . $value,
                0,
                null,
                null
            );
        }
    }

    /**
     * Clear a model field so it is omitted from serialization.
     * Setters reject null for non-nullable fields; ArrayAccess sets container to null.
     *
     * @param mixed $model
     * @param string $property
     * @return void
     */
    private static function clearField($model, string $property): void
    {
        if ($model === null) {
            return;
        }
        $model->offsetSet($property, null);
    }

    /**
     * @param string|null $value
     * @param string $fieldPath
     * @return void
     * @throws ApiException
     */
    private static function validateAccountTypeValue($value, string $fieldPath): void
    {
        if (!in_array($value, self::ALLOWED_ACCOUNT_TYPES, true)) {
            throw new ApiException(
                $fieldPath . ' must be one of [MERCHANT_DEPOSIT_ACCOUNT, SETTLEMENT_ACCOUNT, DIVISION_DEPOSIT_ACCOUNT]; got '
                    . (string) $value,
                0,
                null,
                null
            );
        }
    }

    /**
     * @param string|null $value
     * @param string $fieldPath
     * @return void
     * @throws ApiException
     */
    private static function requireNonEmpty($value, string $fieldPath): void
    {
        if ($value === null || trim((string) $value) === '') {
            throw new ApiException(
                $fieldPath . ' is required and cannot be empty',
                0,
                null,
                null
            );
        }
    }

    /**
     * In sandbox, accountType, beneficiaryAccountName, externalDivisionId,
     * and chargeTarget are ignored (cleared before send).
     *
     * @param mixed $request
     * @return void
     */
    private static function stripSandboxIgnoredFieldsBankAccountInquiry($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        if (!method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        self::clearField($additionalInfo, 'accountType');
        self::clearField($additionalInfo, 'beneficiaryAccountName');
        self::clearField($additionalInfo, 'externalDivisionId');
        self::clearField($additionalInfo, 'chargeTarget');
    }

    /**
     * In sandbox, top-level accountType plus additionalInfo beneficiary/division charge fields are ignored.
     *
     * @param mixed $request
     * @return void
     */
    private static function stripSandboxIgnoredFieldsTransferToBank($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        self::clearField($request, 'accountType');
        if (method_exists($request, 'getAdditionalInfo')) {
            $additionalInfo = $request->getAdditionalInfo();
            if ($additionalInfo !== null) {
                self::clearField($additionalInfo, 'beneficiaryAccountName');
                self::clearField($additionalInfo, 'externalDivisionId');
                self::clearField($additionalInfo, 'chargeTarget');
            }
        }
    }

    /**
     * In sandbox, additionalInfo.accountType, additionalInfo.externalDivisionId,
     * and additionalInfo.chargeTarget are ignored.
     *
     * @param mixed $request
     * @return void
     */
    private static function stripSandboxIgnoredFieldsTransferToDana($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        if (!method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        self::clearField($additionalInfo, 'accountType');
        self::clearField($additionalInfo, 'externalDivisionId');
        self::clearField($additionalInfo, 'chargeTarget');
    }

    /**
     * In sandbox, additionalInfo.externalDivisionId and additionalInfo.chargeTarget are ignored.
     *
     * @param mixed $request
     * @return void
     */
    private static function stripSandboxIgnoredFieldsDanaAccountInquiry($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        if (!method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        self::clearField($additionalInfo, 'externalDivisionId');
        self::clearField($additionalInfo, 'chargeTarget');
    }

    /**
     * Non-sandbox: if accountType is set, it must be a valid enum value. Empty is allowed (no default).
     *
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateAccountTypeBankAccountInquiry($request)
    {
        if ($request === null || self::isSandbox() || !method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        $accountType = method_exists($additionalInfo, 'getAccountType') ? $additionalInfo->getAccountType() : null;
        if ($accountType === null || trim((string) $accountType) === '') {
            return;
        }
        self::validateAccountTypeValue(trim((string) $accountType), 'additionalInfo.accountType');
    }

    /**
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateAccountTypeTransferToBank($request)
    {
        if ($request === null || self::isSandbox()) {
            return;
        }
        $accountType = method_exists($request, 'getAccountType') ? $request->getAccountType() : null;
        if ($accountType === null || trim((string) $accountType) === '') {
            return;
        }
        self::validateAccountTypeValue(trim((string) $accountType), 'accountType');
    }

    /**
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateAccountTypeTransferToDana($request)
    {
        if ($request === null || self::isSandbox() || !method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        $accountType = method_exists($additionalInfo, 'getAccountType') ? $additionalInfo->getAccountType() : null;
        if ($accountType === null || trim((string) $accountType) === '') {
            return;
        }
        self::validateAccountTypeValue(trim((string) $accountType), 'additionalInfo.accountType');
    }

    /**
     * In sandbox, beneficiaryAccountNumber must be 2460888509 and beneficiaryBankCode must be 014.
     *
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateSandboxBeneficiaryBankAccountInquiry($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        $accountNumber = method_exists($request, 'getBeneficiaryAccountNumber')
            ? $request->getBeneficiaryAccountNumber()
            : null;
        if (trim((string) $accountNumber) !== self::SANDBOX_BENEFICIARY_ACCOUNT_NUMBER) {
            throw new ApiException(
                'In sandbox, beneficiaryAccountNumber must be ' . self::SANDBOX_BENEFICIARY_ACCOUNT_NUMBER
                    . '; got ' . (string) $accountNumber,
                0,
                null,
                null
            );
        }
        $bankCode = null;
        if (method_exists($request, 'getAdditionalInfo')) {
            $additionalInfo = $request->getAdditionalInfo();
            if ($additionalInfo !== null && method_exists($additionalInfo, 'getBeneficiaryBankCode')) {
                $bankCode = $additionalInfo->getBeneficiaryBankCode();
            }
        }
        if (trim((string) $bankCode) !== self::SANDBOX_BENEFICIARY_BANK_CODE) {
            throw new ApiException(
                'In sandbox, additionalInfo.beneficiaryBankCode must be ' . self::SANDBOX_BENEFICIARY_BANK_CODE
                    . '; got ' . (string) $bankCode,
                0,
                null,
                null
            );
        }
    }

    /**
     * In sandbox, beneficiaryAccountNumber must be 2460888509 and beneficiaryBankCode must be 014.
     *
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateSandboxBeneficiaryTransferToBank($request)
    {
        if ($request === null || !self::isSandbox()) {
            return;
        }
        $accountNumber = method_exists($request, 'getBeneficiaryAccountNumber')
            ? $request->getBeneficiaryAccountNumber()
            : null;
        if (trim((string) $accountNumber) !== self::SANDBOX_BENEFICIARY_ACCOUNT_NUMBER) {
            throw new ApiException(
                'In sandbox, beneficiaryAccountNumber must be ' . self::SANDBOX_BENEFICIARY_ACCOUNT_NUMBER
                    . '; got ' . (string) $accountNumber,
                0,
                null,
                null
            );
        }
        $bankCode = method_exists($request, 'getBeneficiaryBankCode')
            ? $request->getBeneficiaryBankCode()
            : null;
        if (trim((string) $bankCode) !== self::SANDBOX_BENEFICIARY_BANK_CODE) {
            throw new ApiException(
                'In sandbox, beneficiaryBankCode must be ' . self::SANDBOX_BENEFICIARY_BANK_CODE
                    . '; got ' . (string) $bankCode,
                0,
                null,
                null
            );
        }
    }

    /**
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateRequiredAdditionalInfoNotEmptyBankAccountInquiry($request)
    {
        if ($request === null || !method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        $fundType = method_exists($additionalInfo, 'getFundType') ? $additionalInfo->getFundType() : null;
        self::requireNonEmpty($fundType, 'additionalInfo.fundType');
        $beneficiaryBankCode = method_exists($additionalInfo, 'getBeneficiaryBankCode')
            ? $additionalInfo->getBeneficiaryBankCode()
            : null;
        self::requireNonEmpty($beneficiaryBankCode, 'additionalInfo.beneficiaryBankCode');
    }

    /**
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateRequiredAdditionalInfoNotEmptyTransferToBank($request)
    {
        if ($request === null || !method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        $fundType = method_exists($additionalInfo, 'getFundType') ? $additionalInfo->getFundType() : null;
        self::requireNonEmpty($fundType, 'additionalInfo.fundType');
    }

    /**
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateRequiredAdditionalInfoNotEmptyTransferToDana($request)
    {
        if ($request === null || !method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        $fundType = method_exists($additionalInfo, 'getFundType') ? $additionalInfo->getFundType() : null;
        self::requireNonEmpty($fundType, 'additionalInfo.fundType');
    }

    /**
     * @param mixed $request
     * @return void
     * @throws ApiException
     */
    private static function validateRequiredAdditionalInfoNotEmptyDanaAccountInquiry($request)
    {
        if ($request === null || !method_exists($request, 'getAdditionalInfo')) {
            return;
        }
        $additionalInfo = $request->getAdditionalInfo();
        if ($additionalInfo === null) {
            return;
        }
        $fundType = method_exists($additionalInfo, 'getFundType') ? $additionalInfo->getFundType() : null;
        self::requireNonEmpty($fundType, 'additionalInfo.fundType');
    }
}
